//! OCI-isolated process sandbox runner (WI-0205 D3).
//!
//! Authoritative production isolation is the W014-controlled OCI/container
//! backend (`docker run`, see `super::oci`). The runner never executes the
//! parser on the host filesystem and never exposes the host root.
//!
//! Hard guarantees:
//! - No host-root bind (read-only or otherwise) and no broad host filesystem
//!   read allowance remain in the authoritative policy.
//! - Only the approved `docker` backend is accepted as isolation authority.
//!   Arbitrary existing executables are rejected even when the path exists.
//! - Stored and environment-provided wrapper arguments are NEVER honored as
//!   isolation policy: the mandatory OCI argument vector is generated by W014
//!   from the validated frozen profile on every execution.
//! - CPU capacity (`<=2 vCPU`) is enforced via container CFS quota
//!   (`--cpus`), not via accumulated-CPU-time accounting. Resource,
//!   privilege, and isolation setup failures fail closed.
//! - stdin carries ONLY the scoped single-object bytes; stdout/stderr are
//!   hard-bounded during streaming consumption; wall-clock timeout kills and
//!   reaps the container; no product credentials enter the container.

use std::path::PathBuf;
use std::process::Stdio;
use std::time::{Duration, Instant};

use async_trait::async_trait;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::process::Command;

use super::error::SandboxError;
use super::input::SandboxInput;
use super::oci::{DEFAULT_OCI_IMAGE, build_docker_run_argv, resolve_approved_docker_binary};
use super::output::SandboxOutput;
use super::profile::{
    FROZEN_MAX_CPU_CORES, FROZEN_MAX_MEMORY_BYTES, FROZEN_MAX_OUTPUT_BYTES, FROZEN_MAX_PIDS,
    FROZEN_MAX_TMPFS_BYTES, FROZEN_MAX_WALL_CLOCK_SECS, SandboxSecurityProfile,
};
use super::traits::SandboxRunner;

/// Environment variable selecting the parser sandbox OCI backend binary path.
///
/// Only the approved `docker` backend is accepted. Any other executable name
/// fails closed with `UNAPPROVED_ISOLATION_BACKEND`, even if the path exists.
pub const ENV_PARSER_SANDBOX_WRAPPER_BIN: &str = "W014_PARSER_SANDBOX_WRAPPER_BIN";

/// Legacy environment variable for wrapper arguments (retained for API
/// compatibility only).
///
/// These arguments are NEVER honored: mandatory OCI isolation arguments are
/// generated by W014 on every execution and configuration cannot weaken them.
pub const ENV_PARSER_SANDBOX_WRAPPER_ARGS: &str = "W014_PARSER_SANDBOX_WRAPPER_ARGS";

/// Process sandbox runner launching the parser inside the authoritative OCI sandbox.
#[derive(Debug, Clone)]
pub struct ProcessSandboxRunner {
    /// In-image parser binary path/name executed inside the container.
    ///
    /// This path is NEVER executed on the host. Production value is
    /// `w014-parser-sandbox`, resolved inside the OCI image `PATH`.
    pub binary_path: PathBuf,
    /// Static CLI arguments passed to the in-image parser binary.
    pub extra_args: Vec<String>,
    /// Optional explicitly configured isolation backend binary.
    ///
    /// Only `docker` is accepted at resolution time.
    pub wrapper_binary: Option<PathBuf>,
    /// Stored wrapper arguments (retained for API compatibility; NEVER honored).
    pub wrapper_args: Vec<String>,
    /// OCI image reference carrying the concrete parser binary.
    pub oci_image: String,
}

impl ProcessSandboxRunner {
    /// Creates a new `ProcessSandboxRunner` targeting the in-image parser binary.
    #[must_use]
    pub fn new(binary_path: impl Into<PathBuf>) -> Self {
        Self {
            binary_path: binary_path.into(),
            extra_args: Vec::new(),
            wrapper_binary: None,
            wrapper_args: Vec::new(),
            oci_image: DEFAULT_OCI_IMAGE.to_string(),
        }
    }

    /// Adds extra static CLI arguments consumed by the in-image parser binary.
    #[must_use]
    pub fn with_args(mut self, args: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.extra_args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Configures the isolation backend binary selector.
    ///
    /// Only the approved `docker` backend resolves successfully; all other
    /// executables fail closed at execution time. Supplied `args` are stored
    /// for compatibility but NEVER honored as isolation policy.
    #[must_use]
    pub fn with_wrapper(
        mut self,
        wrapper: impl Into<PathBuf>,
        args: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        self.wrapper_binary = Some(wrapper.into());
        self.wrapper_args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Overrides the OCI image reference (primarily for tests).
    ///
    /// Isolation flags remain W014-generated regardless of image selection.
    #[must_use]
    pub fn with_oci_image(mut self, image: impl Into<String>) -> Self {
        self.oci_image = image.into();
        self
    }

    /// Discovers the platform-default isolation backend (`docker`, if present).
    ///
    /// Returns the approved backend binary with no caller-controlled
    /// arguments; mandatory isolation arguments are generated per execution.
    /// Returns `None` when the approved backend is absent (callers fail closed).
    #[must_use]
    pub fn platform_default_wrapper() -> Option<(PathBuf, Vec<String>)> {
        super::oci::discover_docker_binary().map(|path| (path, Vec::new()))
    }

    /// Configures the platform-default approved isolation backend if available.
    #[must_use]
    pub fn with_platform_wrapper(mut self) -> Self {
        if let Some((wrapper_bin, wrapper_args)) = Self::platform_default_wrapper() {
            self.wrapper_binary = Some(wrapper_bin);
            self.wrapper_args = wrapper_args;
        }
        self
    }

    /// Resolves the authoritative isolation backend binary.
    ///
    /// Only the approved `docker` backend is accepted. Stored and
    /// environment-provided wrapper arguments are NEVER returned as policy.
    ///
    /// # Errors
    /// Returns `SandboxError::SandboxViolation` with:
    /// - `UNAPPROVED_ISOLATION_BACKEND` for any non-`docker` backend,
    /// - `ISOLATION_WRAPPER_NOT_FOUND` when the approved backend is absent,
    /// - `MISSING_ISOLATION_WRAPPER` when no backend is available.
    pub fn resolve_isolation_wrapper(&self) -> Result<(PathBuf, Vec<String>), SandboxError> {
        let docker = resolve_approved_docker_binary(self.wrapper_binary.as_ref())?;
        // Mandatory OCI arguments are generated per execution from the frozen
        // profile; no caller-controlled wrapper arguments are ever honored.
        Ok((docker, Vec::new()))
    }

    /// Builds the full authoritative OCI command for this runner.
    ///
    /// # Errors
    /// Fails closed when the profile violates frozen boundaries, the backend
    /// is unapproved/missing, or the image/binary reference is invalid.
    pub fn build_oci_command(
        &self,
        profile: &SandboxSecurityProfile,
        input: &SandboxInput,
    ) -> Result<(PathBuf, Vec<String>), SandboxError> {
        let (docker, _) = self.resolve_isolation_wrapper()?;
        let argv = build_docker_run_argv(
            profile,
            &self.oci_image,
            &self.binary_path.to_string_lossy(),
            &self.extra_args,
            input,
        )?;
        Ok((docker, argv))
    }

    /// Validates that all mandatory frozen sandbox boundary invariants hold.
    ///
    /// # Errors
    /// Fails closed if any security profile setting violates frozen limits.
    pub(crate) fn validate_frozen_boundary_for_oci(
        profile: &SandboxSecurityProfile,
    ) -> Result<(), SandboxError> {
        Self::validate_frozen_boundary(profile)
    }

    /// Validates that all mandatory frozen sandbox boundary invariants hold.
    ///
    /// # Errors
    /// Fails closed if any security profile setting violates frozen limits or allows unsandboxed execution.
    fn validate_frozen_boundary(profile: &SandboxSecurityProfile) -> Result<(), SandboxError> {
        profile
            .validate()
            .map_err(|detail| SandboxError::SandboxViolation {
                violation_type: "INVALID_PROFILE".to_string(),
                detail,
            })?;

        // 1. Non-root execution
        if !profile.process.run_as_non_root || profile.process.uid == 0 || profile.process.gid == 0
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "ROOT_EXECUTION_FORBIDDEN".to_string(),
                detail: "Sandbox must execute as unprivileged non-root user (uid/gid != 0)"
                    .to_string(),
            });
        }

        // 2. Privilege boundary
        if !profile.process.no_new_privileges {
            return Err(SandboxError::SandboxViolation {
                violation_type: "PRIVILEGE_ESCALATION_FORBIDDEN".to_string(),
                detail: "Sandbox must enforce no-new-privileges".to_string(),
            });
        }
        if !profile.process.drop_all_capabilities {
            return Err(SandboxError::SandboxViolation {
                violation_type: "CAPABILITY_REDUCTION_REQUIRED".to_string(),
                detail: "Sandbox must drop all capabilities".to_string(),
            });
        }

        // 3. Filesystem isolation
        if !profile.filesystem.root_readonly {
            return Err(SandboxError::SandboxViolation {
                violation_type: "READONLY_ROOT_REQUIRED".to_string(),
                detail: "Sandbox root filesystem must be read-only".to_string(),
            });
        }
        if profile.filesystem.tmpfs_max_bytes > FROZEN_MAX_TMPFS_BYTES {
            return Err(SandboxError::SandboxViolation {
                violation_type: "TMPFS_CEILING_EXCEEDED".to_string(),
                detail: format!(
                    "TMPFS scratch limit {} exceeds 1 GiB ceiling",
                    profile.filesystem.tmpfs_max_bytes
                ),
            });
        }
        if profile.filesystem.allow_host_mounts
            || profile.filesystem.allow_secret_mounts
            || profile.filesystem.allow_docker_socket
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "UNAUTHORIZED_MOUNTS_FORBIDDEN".to_string(),
                detail: "Host mounts, secret mounts, and docker sockets are strictly forbidden"
                    .to_string(),
            });
        }

        // 4. Network isolation
        if profile.network.allow_public_ingress
            || profile.network.allow_general_egress
            || profile.network.allow_ai_provider_access
            || profile.network.allow_external_urls
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "NETWORK_ACCESS_FORBIDDEN".to_string(),
                detail: "All network ingress, egress, AI access, and external URLs are forbidden"
                    .to_string(),
            });
        }

        // 5. Ceilings
        if profile.ceilings.max_cpu_cores > FROZEN_MAX_CPU_CORES
            || profile.ceilings.max_memory_bytes > FROZEN_MAX_MEMORY_BYTES
            || profile.ceilings.max_pids > FROZEN_MAX_PIDS
            || profile.ceilings.max_wall_clock_seconds > FROZEN_MAX_WALL_CLOCK_SECS
            || profile.ceilings.max_output_bytes > FROZEN_MAX_OUTPUT_BYTES
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "RESOURCE_CEILING_EXCEEDED".to_string(),
                detail: "Resource ceilings exceed hard frozen maximums".to_string(),
            });
        }

        // 6. Credentials absence
        if profile.credentials.has_database_credentials
            || profile.credentials.has_ai_credentials
            || profile.credentials.has_s3_credentials
            || profile.credentials.has_kms_credentials
            || profile.credentials.has_audit_signing_credentials
            || profile.credentials.has_audit_hmac_keys
            || profile.credentials.has_session_credentials
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "CREDENTIALS_FORBIDDEN".to_string(),
                detail: "Zero application or infrastructure credentials may exist in sandbox"
                    .to_string(),
            });
        }

        Ok(())
    }
}

/// Internal result of streaming consumption of stdout and stderr.
enum StreamResult {
    Success {
        stdout: Vec<u8>,
        stderr: Vec<u8>,
        status: std::process::ExitStatus,
    },
    StdoutOverflow {
        attempted_bytes: usize,
    },
    StderrOverflow {
        attempted_bytes: usize,
    },
    IoError(String),
}

#[async_trait]
impl SandboxRunner for ProcessSandboxRunner {
    async fn run(
        &self,
        profile: &SandboxSecurityProfile,
        input: &SandboxInput,
    ) -> Result<SandboxOutput, SandboxError> {
        // 1. Enforce authoritative frozen security profile validation (Fail Closed).
        // Any privilege, mount, network, ceiling, or credential violation,
        // and any resource-limit setup precondition failure, stops here.
        Self::validate_frozen_boundary(profile)?;

        // 2. Verify input integrity before launching.
        input.verify_integrity().map_err(|detail| {
            SandboxError::OutputValidation(super::output::OutputValidationError::InvalidField {
                field: "input_integrity",
                reason: detail,
            })
        })?;

        // 3. Resolve the approved OCI backend and build the W014-generated
        // mandatory container policy. Unapproved/missing backends fail closed;
        // no caller-controlled isolation arguments are honored.
        let (backend_program, backend_args) = self.build_oci_command(profile, input)?;

        let mut cmd = Command::new(&backend_program);
        cmd.args(&backend_args);

        // Host child environment carries NO product credentials: clear and
        // propagate only PATH so the backend binary resolves safely.
        cmd.env_clear();
        if let Ok(host_path) = std::env::var("PATH") {
            cmd.env("PATH", host_path);
        }

        // NOTE: CPU/memory/PID quotas are enforced by the container runtime
        // flags above (`--cpus`, `--memory`, `--pids-limit`). Accumulated
        // CPU-time accounting is NOT capacity enforcement and is therefore
        // never used as the authoritative vCPU mechanism.

        // Configure stdio: pipe stdin (scoped object bytes only), stdout, stderr.
        cmd.stdin(Stdio::piped());
        cmd.stdout(Stdio::piped());
        cmd.stderr(Stdio::piped());

        // 4. Spawn the OCI backend.
        let mut child = cmd.spawn().map_err(|e| SandboxError::IO {
            detail: format!("Failed to spawn sandbox isolation backend '{backend_program:?}': {e}"),
        })?;

        let mut child_stdin = child.stdin.take().ok_or_else(|| SandboxError::IO {
            detail: "Failed to open sandbox stdin pipe".to_string(),
        })?;

        // Write scoped input bytes to container stdin, then close the pipe.
        let input_bytes = input.bytes.clone();
        let writer_task = tokio::spawn(async move {
            let res = child_stdin.write_all(&input_bytes).await;
            let _ = child_stdin.flush().await;
            drop(child_stdin);
            res
        });

        // 5. Hard Bounded Streaming Output Consumption with Wall-Clock Timeout.
        let max_output_bytes = profile.ceilings.max_output_bytes;
        let max_stderr_bytes = profile.ceilings.max_output_bytes;
        let wall_clock_limit = Duration::from_secs(profile.ceilings.max_wall_clock_seconds);
        let start_instant = Instant::now();

        let mut stdout_pipe = child.stdout.take();
        let mut stderr_pipe = child.stderr.take();

        let stream_future = async {
            let mut stdout_buf = Vec::new();
            let mut stderr_buf = Vec::new();

            let mut stdout_done = stdout_pipe.is_none();
            let mut stderr_done = stderr_pipe.is_none();

            let mut stdout_chunk = [0u8; 8192];
            let mut stderr_chunk = [0u8; 8192];

            loop {
                if stdout_done && stderr_done {
                    break;
                }

                tokio::select! {
                    res = async {
                        if let Some(ref mut out) = stdout_pipe {
                            out.read(&mut stdout_chunk).await
                        } else {
                            std::future::pending().await
                        }
                    }, if !stdout_done => {
                        match res {
                            Ok(0) => {
                                stdout_done = true;
                                stdout_pipe = None;
                            }
                            Ok(n) => {
                                if stdout_buf.len() + n > max_output_bytes {
                                    return StreamResult::StdoutOverflow {
                                        attempted_bytes: stdout_buf.len() + n,
                                    };
                                }
                                stdout_buf.extend_from_slice(&stdout_chunk[..n]);
                            }
                            Err(e) => {
                                return StreamResult::IoError(format!("Error reading sandbox stdout: {e}"));
                            }
                        }
                    }
                    res = async {
                        if let Some(ref mut err) = stderr_pipe {
                            err.read(&mut stderr_chunk).await
                        } else {
                            std::future::pending().await
                        }
                    }, if !stderr_done => {
                        match res {
                            Ok(0) => {
                                stderr_done = true;
                                stderr_pipe = None;
                            }
                            Ok(n) => {
                                if stderr_buf.len() + n > max_stderr_bytes {
                                    return StreamResult::StderrOverflow {
                                        attempted_bytes: stderr_buf.len() + n,
                                    };
                                }
                                stderr_buf.extend_from_slice(&stderr_chunk[..n]);
                            }
                            Err(e) => {
                                return StreamResult::IoError(format!("Error reading sandbox stderr: {e}"));
                            }
                        }
                    }
                }
            }

            match child.wait().await {
                Ok(status) => StreamResult::Success {
                    stdout: stdout_buf,
                    stderr: stderr_buf,
                    status,
                },
                Err(e) => {
                    StreamResult::IoError(format!("Failed waiting for sandbox exit status: {e}"))
                }
            }
        };

        let stream_result = tokio::time::timeout(wall_clock_limit, stream_future).await;
        let _ = writer_task.await;

        let (stdout_bytes, stderr_bytes, status) = match stream_result {
            Ok(StreamResult::Success {
                stdout,
                stderr,
                status,
            }) => (stdout, stderr, status),
            Ok(StreamResult::StdoutOverflow { attempted_bytes }) => {
                // Hard ceiling crossed during stdout streaming: terminate and reap child immediately.
                let _ = child.kill().await;
                let _ = child.wait().await;
                return Err(SandboxError::ResourceViolation {
                    resource: "stdout_output_bytes".to_string(),
                    limit: format!("{max_output_bytes} bytes"),
                    detail: format!(
                        "Sandbox stdout exceeded hard output ceiling of {max_output_bytes} bytes during consumption (attempted {attempted_bytes} bytes)"
                    ),
                });
            }
            Ok(StreamResult::StderrOverflow { attempted_bytes }) => {
                // Hard ceiling crossed during stderr streaming: terminate and reap child immediately.
                let _ = child.kill().await;
                let _ = child.wait().await;
                return Err(SandboxError::ResourceViolation {
                    resource: "stderr_output_bytes".to_string(),
                    limit: format!("{max_stderr_bytes} bytes"),
                    detail: format!(
                        "Sandbox stderr exceeded hard output ceiling of {max_stderr_bytes} bytes during consumption (attempted {attempted_bytes} bytes)"
                    ),
                });
            }
            Ok(StreamResult::IoError(detail)) => {
                let _ = child.kill().await;
                let _ = child.wait().await;
                return Err(SandboxError::IO { detail });
            }
            Err(_) => {
                // Wall-clock timeout fired: kill and reap child immediately.
                let _ = child.kill().await;
                let _ = child.wait().await;
                return Err(SandboxError::Timeout {
                    elapsed_secs: start_instant.elapsed().as_secs(),
                    limit_secs: profile.ceilings.max_wall_clock_seconds,
                });
            }
        };

        let stderr_str = String::from_utf8_lossy(&stderr_bytes).to_string();

        // 6. Check backend exit status. A missing parser binary/image inside
        // the container exits non-zero here and is NEVER treated as success.
        if !status.success() {
            let code = status.code();

            #[cfg(unix)]
            let signal = {
                use std::os::unix::process::ExitStatusExt;
                status.signal()
            };
            #[cfg(not(unix))]
            let signal: Option<i32> = None;

            // Check for OOM exit conditions (exit code 137, SIGKILL (9), or stderr diagnostic).
            if code == Some(137)
                || signal == Some(9)
                || stderr_str.to_lowercase().contains("out of memory")
                || stderr_str.to_lowercase().contains("oom-killer")
            {
                return Err(SandboxError::OutOfMemory { detail: stderr_str });
            }

            // Check for CPU limit signal SIGXCPU (24).
            if signal == Some(24) {
                return Err(SandboxError::ResourceViolation {
                    resource: "CPU".to_string(),
                    limit: format!("{}s", profile.ceilings.max_wall_clock_seconds),
                    detail: "Sandbox killed by SIGXCPU (CPU time limit exceeded)".to_string(),
                });
            }

            return Err(SandboxError::ProcessCrash {
                exit_code: code,
                signal,
                stderr: stderr_str,
            });
        }

        // 7. Verify hard output size bound on received bytes.
        if stdout_bytes.len() > profile.ceilings.max_output_bytes {
            return Err(SandboxError::ResourceViolation {
                resource: "stdout_output_bytes".to_string(),
                limit: format!("{} bytes", profile.ceilings.max_output_bytes),
                detail: format!(
                    "Output size {} bytes exceeds bound {}",
                    stdout_bytes.len(),
                    profile.ceilings.max_output_bytes
                ),
            });
        }

        // 8. Deserialize JSON output envelope.
        let output: SandboxOutput =
            serde_json::from_slice(&stdout_bytes).map_err(|e| SandboxError::MalformedOutput {
                detail: format!("Failed to parse sandbox JSON output: {e}"),
            })?;

        // 9. Authoritative validation against input and domain bounds.
        output
            .validate_against_input(input)
            .map_err(SandboxError::OutputValidation)?;

        Ok(output)
    }
}
