//! OCI-isolated process sandbox runner (WI-0205 D3).
//!
//! Authoritative production isolation is the W014-controlled OCI/container
//! backend (`docker run`, see `super::oci`). The runner never executes the
//! parser on the host filesystem and never exposes the host root.
//!
//! Hard guarantees:
//! - No host-root bind (read-only or otherwise) and no broad host filesystem
//!   read allowance remain in the authoritative policy.
//! - Only the approved `docker` backend is accepted as isolation authority.
//!   Arbitrary existing executables are rejected even when the path exists.
//! - Stored and environment-provided wrapper arguments are NEVER honored as
//!   isolation policy: the mandatory OCI argument vector is generated by W014
//!   from the validated frozen profile on every execution.
//! - CPU capacity (`<=2 vCPU`) is enforced via container CFS quota
//!   (`--cpus`), not via accumulated-CPU-time accounting. Resource,
//!   privilege, and isolation setup failures fail closed.
//! - stdin carries ONLY the scoped single-object bytes; stdout/stderr are
//!   hard-bounded during streaming consumption; no product credentials enter
//!   the container.
//! - ONE authoritative global wall-clock deadline (<=600s) covers the complete
//!   execution lifecycle: OCI launch, stdin handoff, stdout/stderr drain,
//!   container execution, backend wait, and abort processing. The stdin writer
//!   task is always joined inside that deadline (aborted on expiry) and can
//!   never extend execution past it.
//! - Production Docker invocation uses `--pull=never` with a local image
//!   preflight (`w014-parser-sandbox:local` existence + revision/identity
//!   labels); a missing image fails closed without any registry pull.
//! - Every execution mints a W014-generated `--name` identity; abort paths
//!   terminate the ACTUAL OCI container (`docker rm -f <name>`, bounded) and
//!   reap the `docker run` client. Unestablished termination fails closed
//!   instead of reporting an ordinary execution error.

use std::path::PathBuf;
use std::process::Stdio;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use async_trait::async_trait;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::process::Command;

use super::error::SandboxError;
use super::input::SandboxInput;
use super::oci::{
    CLIENT_REAP_TIMEOUT_SECS, DEFAULT_OCI_IMAGE, build_docker_run_argv,
    build_docker_run_argv_with_container_name, generate_container_name, preflight_local_image,
    resolve_approved_docker_binary, terminate_container_by_name,
};
use super::output::SandboxOutput;
use super::profile::{
    FROZEN_MAX_CPU_CORES, FROZEN_MAX_MEMORY_BYTES, FROZEN_MAX_OUTPUT_BYTES, FROZEN_MAX_PIDS,
    FROZEN_MAX_TMPFS_BYTES, FROZEN_MAX_WALL_CLOCK_SECS, SandboxSecurityProfile,
};
use super::traits::SandboxRunner;

/// Environment variable selecting the parser sandbox OCI backend binary path.
///
/// Only the approved `docker` backend is accepted. Any other executable name
/// fails closed with `UNAPPROVED_ISOLATION_BACKEND`, even if the path exists.
pub const ENV_PARSER_SANDBOX_WRAPPER_BIN: &str = "W014_PARSER_SANDBOX_WRAPPER_BIN";

/// Legacy environment variable for wrapper arguments (retained for API
/// compatibility only).
///
/// These arguments are NEVER honored: mandatory OCI isolation arguments are
/// generated by W014 on every execution and configuration cannot weaken them.
pub const ENV_PARSER_SANDBOX_WRAPPER_ARGS: &str = "W014_PARSER_SANDBOX_WRAPPER_ARGS";

/// Process sandbox runner launching the parser inside the authoritative OCI sandbox.
#[derive(Debug, Clone)]
pub struct ProcessSandboxRunner {
    /// In-image parser binary path/name executed inside the container.
    ///
    /// This path is NEVER executed on the host. Production value is
    /// `w014-parser-sandbox`, resolved inside the OCI image `PATH`.
    pub binary_path: PathBuf,
    /// Static CLI arguments passed to the in-image parser binary.
    pub extra_args: Vec<String>,
    /// Optional explicitly configured isolation backend binary.
    ///
    /// Only `docker` is accepted at resolution time.
    pub wrapper_binary: Option<PathBuf>,
    /// Stored wrapper arguments (retained for API compatibility; NEVER honored).
    pub wrapper_args: Vec<String>,
    /// OCI image reference carrying the concrete parser binary.
    pub oci_image: String,
    /// W014-generated container identity of the most recent execution.
    ///
    /// Test/verification observability only: lets lifecycle tests prove the
    /// actual OCI container was terminated and removed. Never read as policy.
    last_container_name: Arc<Mutex<Option<String>>>,
}

impl ProcessSandboxRunner {
    /// Creates a new `ProcessSandboxRunner` targeting the in-image parser binary.
    #[must_use]
    pub fn new(binary_path: impl Into<PathBuf>) -> Self {
        Self {
            binary_path: binary_path.into(),
            extra_args: Vec::new(),
            wrapper_binary: None,
            wrapper_args: Vec::new(),
            oci_image: DEFAULT_OCI_IMAGE.to_string(),
            last_container_name: Arc::new(Mutex::new(None)),
        }
    }

    /// Adds extra static CLI arguments consumed by the in-image parser binary.
    #[must_use]
    pub fn with_args(mut self, args: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.extra_args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Configures the isolation backend binary selector.
    ///
    /// Only the approved `docker` backend resolves successfully; all other
    /// executables fail closed at execution time. Supplied `args` are stored
    /// for compatibility but NEVER honored as isolation policy.
    #[must_use]
    pub fn with_wrapper(
        mut self,
        wrapper: impl Into<PathBuf>,
        args: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        self.wrapper_binary = Some(wrapper.into());
        self.wrapper_args = args.into_iter().map(Into::into).collect();
        self
    }

    /// Overrides the OCI image reference (primarily for tests).
    ///
    /// Isolation flags remain W014-generated regardless of image selection.
    #[must_use]
    pub fn with_oci_image(mut self, image: impl Into<String>) -> Self {
        self.oci_image = image.into();
        self
    }

    /// Discovers the platform-default isolation backend (`docker`, if present).
    ///
    /// Returns the approved backend binary with no caller-controlled
    /// arguments; mandatory isolation arguments are generated per execution.
    /// Returns `None` when the approved backend is absent (callers fail closed).
    #[must_use]
    pub fn platform_default_wrapper() -> Option<(PathBuf, Vec<String>)> {
        super::oci::discover_docker_binary().map(|path| (path, Vec::new()))
    }

    /// Configures the platform-default approved isolation backend if available.
    #[must_use]
    pub fn with_platform_wrapper(mut self) -> Self {
        if let Some((wrapper_bin, wrapper_args)) = Self::platform_default_wrapper() {
            self.wrapper_binary = Some(wrapper_bin);
            self.wrapper_args = wrapper_args;
        }
        self
    }

    /// Returns the W014-generated container identity of the most recent
    /// execution, if any.
    ///
    /// Test/verification observability only: lets lifecycle tests prove the
    /// actual OCI container was terminated and removed. The identity is
    /// server-generated per execution and never derived from browser input,
    /// job payloads, document bytes, or parser output.
    #[must_use]
    pub fn last_container_name(&self) -> Option<String> {
        self.last_container_name
            .lock()
            .ok()
            .and_then(|guard| guard.clone())
    }

    /// Records the W014-generated container identity for the current execution.
    fn record_container_name(&self, container_name: &str) {
        if let Ok(mut guard) = self.last_container_name.lock() {
            *guard = Some(container_name.to_string());
        }
    }

    /// Resolves the authoritative isolation backend binary.
    ///
    /// Only the approved `docker` backend is accepted. Stored and
    /// environment-provided wrapper arguments are NEVER returned as policy.
    ///
    /// # Errors
    /// Returns `SandboxError::SandboxViolation` with:
    /// - `UNAPPROVED_ISOLATION_BACKEND` for any non-`docker` backend,
    /// - `ISOLATION_WRAPPER_NOT_FOUND` when the approved backend is absent,
    /// - `MISSING_ISOLATION_WRAPPER` when no backend is available.
    pub fn resolve_isolation_wrapper(&self) -> Result<(PathBuf, Vec<String>), SandboxError> {
        let docker = resolve_approved_docker_binary(self.wrapper_binary.as_ref())?;
        // Mandatory OCI arguments are generated per execution from the frozen
        // profile; no caller-controlled wrapper arguments are ever honored.
        Ok((docker, Vec::new()))
    }

    /// Builds the full authoritative OCI command for this runner.
    ///
    /// # Errors
    /// Fails closed when the profile violates frozen boundaries, the backend
    /// is unapproved/missing, or the image/binary reference is invalid.
    pub fn build_oci_command(
        &self,
        profile: &SandboxSecurityProfile,
        input: &SandboxInput,
    ) -> Result<(PathBuf, Vec<String>), SandboxError> {
        let (docker, _) = self.resolve_isolation_wrapper()?;
        let argv = build_docker_run_argv(
            profile,
            &self.oci_image,
            &self.binary_path.to_string_lossy(),
            &self.extra_args,
            input,
        )?;
        Ok((docker, argv))
    }

    /// Validates that all mandatory frozen sandbox boundary invariants hold.
    ///
    /// # Errors
    /// Fails closed if any security profile setting violates frozen limits.
    pub(crate) fn validate_frozen_boundary_for_oci(
        profile: &SandboxSecurityProfile,
    ) -> Result<(), SandboxError> {
        Self::validate_frozen_boundary(profile)
    }

    /// Validates that all mandatory frozen sandbox boundary invariants hold.
    ///
    /// # Errors
    /// Fails closed if any security profile setting violates frozen limits or allows unsandboxed execution.
    fn validate_frozen_boundary(profile: &SandboxSecurityProfile) -> Result<(), SandboxError> {
        profile
            .validate()
            .map_err(|detail| SandboxError::SandboxViolation {
                violation_type: "INVALID_PROFILE".to_string(),
                detail,
            })?;

        // 1. Non-root execution
        if !profile.process.run_as_non_root || profile.process.uid == 0 || profile.process.gid == 0
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "ROOT_EXECUTION_FORBIDDEN".to_string(),
                detail: "Sandbox must execute as unprivileged non-root user (uid/gid != 0)"
                    .to_string(),
            });
        }

        // 2. Privilege boundary
        if !profile.process.no_new_privileges {
            return Err(SandboxError::SandboxViolation {
                violation_type: "PRIVILEGE_ESCALATION_FORBIDDEN".to_string(),
                detail: "Sandbox must enforce no-new-privileges".to_string(),
            });
        }
        if !profile.process.drop_all_capabilities {
            return Err(SandboxError::SandboxViolation {
                violation_type: "CAPABILITY_REDUCTION_REQUIRED".to_string(),
                detail: "Sandbox must drop all capabilities".to_string(),
            });
        }

        // 3. Filesystem isolation
        if !profile.filesystem.root_readonly {
            return Err(SandboxError::SandboxViolation {
                violation_type: "READONLY_ROOT_REQUIRED".to_string(),
                detail: "Sandbox root filesystem must be read-only".to_string(),
            });
        }
        if profile.filesystem.tmpfs_max_bytes > FROZEN_MAX_TMPFS_BYTES {
            return Err(SandboxError::SandboxViolation {
                violation_type: "TMPFS_CEILING_EXCEEDED".to_string(),
                detail: format!(
                    "TMPFS scratch limit {} exceeds 1 GiB ceiling",
                    profile.filesystem.tmpfs_max_bytes
                ),
            });
        }
        if profile.filesystem.allow_host_mounts
            || profile.filesystem.allow_secret_mounts
            || profile.filesystem.allow_docker_socket
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "UNAUTHORIZED_MOUNTS_FORBIDDEN".to_string(),
                detail: "Host mounts, secret mounts, and docker sockets are strictly forbidden"
                    .to_string(),
            });
        }

        // 4. Network isolation
        if profile.network.allow_public_ingress
            || profile.network.allow_general_egress
            || profile.network.allow_ai_provider_access
            || profile.network.allow_external_urls
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "NETWORK_ACCESS_FORBIDDEN".to_string(),
                detail: "All network ingress, egress, AI access, and external URLs are forbidden"
                    .to_string(),
            });
        }

        // 5. Ceilings
        if profile.ceilings.max_cpu_cores > FROZEN_MAX_CPU_CORES
            || profile.ceilings.max_memory_bytes > FROZEN_MAX_MEMORY_BYTES
            || profile.ceilings.max_pids > FROZEN_MAX_PIDS
            || profile.ceilings.max_wall_clock_seconds > FROZEN_MAX_WALL_CLOCK_SECS
            || profile.ceilings.max_output_bytes > FROZEN_MAX_OUTPUT_BYTES
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "RESOURCE_CEILING_EXCEEDED".to_string(),
                detail: "Resource ceilings exceed hard frozen maximums".to_string(),
            });
        }

        // 6. Credentials absence
        if profile.credentials.has_database_credentials
            || profile.credentials.has_ai_credentials
            || profile.credentials.has_s3_credentials
            || profile.credentials.has_kms_credentials
            || profile.credentials.has_audit_signing_credentials
            || profile.credentials.has_audit_hmac_keys
            || profile.credentials.has_session_credentials
        {
            return Err(SandboxError::SandboxViolation {
                violation_type: "CREDENTIALS_FORBIDDEN".to_string(),
                detail: "Zero application or infrastructure credentials may exist in sandbox"
                    .to_string(),
            });
        }

        Ok(())
    }

    /// Aborts execution with the given error after terminating the ACTUAL OCI
    /// container and reaping the backend client.
    ///
    /// A pending stdin writer task is aborted (never awaited unboundedly and
    /// never polled after completion), remaining pipes are dropped by the
    /// caller, `docker rm -f <name>` terminates the real container (bounded),
    /// and the `docker run` client is killed and reaped (bounded). When
    /// actual-container termination cannot be established, the termination
    /// failure is returned INSTEAD of `err` (fail closed: never report an
    /// ordinary execution error while a parser container may remain alive).
    async fn abort_with_error(
        backend_program: &std::path::Path,
        container_name: &str,
        child: &mut tokio::process::Child,
        writer_task: &mut Option<tokio::task::JoinHandle<Result<(), std::io::Error>>>,
        err: SandboxError,
    ) -> SandboxError {
        if let Some(handle) = writer_task.take() {
            handle.abort();
            let _ = handle.await;
        }
        match terminate_container_by_name(backend_program, container_name).await {
            Ok(()) => {
                kill_and_reap_client(child).await;
                err
            }
            Err(termination_err) => {
                kill_and_reap_client(child).await;
                termination_err
            }
        }
    }

    /// Aborts execution on global wall-clock expiry (see [`Self::abort_with_error`]).
    async fn abort_with_timeout(
        backend_program: &std::path::Path,
        container_name: &str,
        child: &mut tokio::process::Child,
        writer_task: &mut Option<tokio::task::JoinHandle<Result<(), std::io::Error>>>,
        elapsed_secs: u64,
        limit_secs: u64,
    ) -> SandboxError {
        Self::abort_with_error(
            backend_program,
            container_name,
            child,
            writer_task,
            SandboxError::Timeout {
                elapsed_secs,
                limit_secs,
            },
        )
        .await
    }
}

/// Kills (if still running) and reaps the `docker run` backend client.
///
/// Bounded: the reap wait itself cannot block indefinitely.
async fn kill_and_reap_client(child: &mut tokio::process::Child) {
    let _ = child.kill().await;
    let _ = tokio::time::timeout(Duration::from_secs(CLIENT_REAP_TIMEOUT_SECS), child.wait()).await;
}

/// Concurrently drains stdout/stderr to hard bounds, then waits for the backend.
///
/// The caller bounds this future with the single authoritative global
/// wall-clock deadline and retains ownership of `child` so abort paths can
/// still kill and reap the client after this future is dropped.
async fn drain_and_wait(
    child: &mut tokio::process::Child,
    mut stdout_pipe: Option<tokio::process::ChildStdout>,
    mut stderr_pipe: Option<tokio::process::ChildStderr>,
    max_output_bytes: usize,
    max_stderr_bytes: usize,
) -> StreamResult {
    let mut stdout_buf = Vec::new();
    let mut stderr_buf = Vec::new();

    let mut stdout_done = stdout_pipe.is_none();
    let mut stderr_done = stderr_pipe.is_none();

    let mut stdout_chunk = [0u8; 8192];
    let mut stderr_chunk = [0u8; 8192];

    loop {
        if stdout_done && stderr_done {
            break;
        }

        tokio::select! {
            res = async {
                if let Some(ref mut out) = stdout_pipe {
                    out.read(&mut stdout_chunk).await
                } else {
                    std::future::pending().await
                }
            }, if !stdout_done => {
                match res {
                    Ok(0) => {
                        stdout_done = true;
                        stdout_pipe = None;
                    }
                    Ok(n) => {
                        if stdout_buf.len() + n > max_output_bytes {
                            return StreamResult::StdoutOverflow {
                                attempted_bytes: stdout_buf.len() + n,
                            };
                        }
                        stdout_buf.extend_from_slice(&stdout_chunk[..n]);
                    }
                    Err(e) => {
                        return StreamResult::IoError(format!("Error reading sandbox stdout: {e}"));
                    }
                }
            }
            res = async {
                if let Some(ref mut err) = stderr_pipe {
                    err.read(&mut stderr_chunk).await
                } else {
                    std::future::pending().await
                }
            }, if !stderr_done => {
                match res {
                    Ok(0) => {
                        stderr_done = true;
                        stderr_pipe = None;
                    }
                    Ok(n) => {
                        if stderr_buf.len() + n > max_stderr_bytes {
                            return StreamResult::StderrOverflow {
                                attempted_bytes: stderr_buf.len() + n,
                            };
                        }
                        stderr_buf.extend_from_slice(&stderr_chunk[..n]);
                    }
                    Err(e) => {
                        return StreamResult::IoError(format!("Error reading sandbox stderr: {e}"));
                    }
                }
            }
        }
    }

    match child.wait().await {
        Ok(status) => StreamResult::Success {
            stdout: stdout_buf,
            stderr: stderr_buf,
            status,
        },
        Err(e) => StreamResult::IoError(format!("Failed waiting for sandbox exit status: {e}")),
    }
}

/// Internal result of streaming consumption of stdout and stderr.
enum StreamResult {
    Success {
        stdout: Vec<u8>,
        stderr: Vec<u8>,
        status: std::process::ExitStatus,
    },
    StdoutOverflow {
        attempted_bytes: usize,
    },
    StderrOverflow {
        attempted_bytes: usize,
    },
    IoError(String),
}

#[async_trait]
impl SandboxRunner for ProcessSandboxRunner {
    async fn run(
        &self,
        profile: &SandboxSecurityProfile,
        input: &SandboxInput,
    ) -> Result<SandboxOutput, SandboxError> {
        // 1. Enforce authoritative frozen security profile validation (Fail Closed).
        // Any privilege, mount, network, ceiling, or credential violation,
        // and any resource-limit setup precondition failure, stops here.
        Self::validate_frozen_boundary(profile)?;

        // 2. Verify input integrity before launching.
        input.verify_integrity().map_err(|detail| {
            SandboxError::OutputValidation(super::output::OutputValidationError::InvalidField {
                field: "input_integrity",
                reason: detail,
            })
        })?;

        // 3. Resolve the approved OCI backend, mint the W014-generated
        // actual-container identity, and build the mandatory container policy
        // (`--pull=never`, `--name`, hardening). Unapproved/missing backends
        // fail closed; no caller-controlled isolation arguments are honored.
        let (backend_program, _) = self.resolve_isolation_wrapper()?;
        let container_name = generate_container_name();
        self.record_container_name(&container_name);
        let backend_args = build_docker_run_argv_with_container_name(
            profile,
            &self.oci_image,
            &self.binary_path.to_string_lossy(),
            &self.extra_args,
            input,
            &container_name,
        )?;

        // 4. ONE authoritative global wall-clock deadline (<=600s) covering the
        // COMPLETE execution lifecycle: local image preflight, OCI launch,
        // stdin handoff, stdout/stderr drain, container execution, backend
        // wait, and abort processing. Every phase below is bounded by this
        // single `deadline`; the stdin writer is always joined inside it
        // (aborted on expiry) and can never extend execution past it.
        let wall_clock_limit = Duration::from_secs(profile.ceilings.max_wall_clock_seconds);
        let start_instant = Instant::now();
        let deadline = tokio::time::Instant::now() + wall_clock_limit;
        let max_wall_clock_seconds = profile.ceilings.max_wall_clock_seconds;

        // Local image preflight inside the same deadline: missing images,
        // inspect failures, and revision/identity violations fail closed here,
        // before any parser output can be accepted. No pull is ever attempted.
        let preflight_outcome = tokio::select! {
            res = preflight_local_image(&backend_program, &self.oci_image) => Some(res),
            () = tokio::time::sleep_until(deadline) => None,
        };
        match preflight_outcome {
            None => {
                return Err(SandboxError::Timeout {
                    elapsed_secs: start_instant.elapsed().as_secs(),
                    limit_secs: max_wall_clock_seconds,
                });
            }
            Some(Err(preflight_err)) => return Err(preflight_err),
            Some(Ok(())) => {}
        }

        // NOTE: CPU/memory/PID quotas are enforced by the container runtime
        // flags above (`--cpus`, `--memory`, `--pids-limit`). Accumulated
        // CPU-time accounting is NOT capacity enforcement and is therefore
        // never used as the authoritative vCPU mechanism.

        // Configure stdio: pipe stdin (scoped object bytes only), stdout, stderr.
        let mut cmd = Command::new(&backend_program);
        cmd.args(&backend_args);

        // Host child environment carries NO product credentials: clear and
        // propagate only PATH so the backend binary resolves safely.
        cmd.env_clear();
        if let Ok(host_path) = std::env::var("PATH") {
            cmd.env("PATH", host_path);
        }
        cmd.stdin(Stdio::piped());
        cmd.stdout(Stdio::piped());
        cmd.stderr(Stdio::piped());
        cmd.kill_on_drop(true);

        // 5. Launch the OCI backend inside the global deadline window.
        if tokio::time::Instant::now() >= deadline {
            return Err(SandboxError::Timeout {
                elapsed_secs: start_instant.elapsed().as_secs(),
                limit_secs: max_wall_clock_seconds,
            });
        }
        let mut child = cmd.spawn().map_err(|e| SandboxError::IO {
            detail: format!("Failed to spawn sandbox isolation backend '{backend_program:?}': {e}"),
        })?;

        let child_stdin = match child.stdin.take() {
            Some(stdin) => stdin,
            None => {
                let io_err = SandboxError::IO {
                    detail: "Failed to open sandbox stdin pipe".to_string(),
                };
                match terminate_container_by_name(&backend_program, &container_name).await {
                    Ok(()) => {
                        kill_and_reap_client(&mut child).await;
                        return Err(io_err);
                    }
                    Err(termination_err) => {
                        kill_and_reap_client(&mut child).await;
                        return Err(termination_err);
                    }
                }
            }
        };

        // 6. stdin handoff progresses CONCURRENTLY with the stdout/stderr drain
        // below (never "write everything then read", never "read without
        // progressing stdin"). The writer is joined inside the same global
        // deadline and aborted on expiry.
        let input_bytes = input.bytes.clone();
        let mut writer_task: Option<tokio::task::JoinHandle<Result<(), std::io::Error>>> =
            Some(tokio::spawn(async move {
                let mut stdin = child_stdin;
                let res = stdin.write_all(&input_bytes).await;
                let _ = stdin.flush().await;
                drop(stdin);
                res
            }));

        // 7. Hard-bounded concurrent streaming consumption under the SAME
        // global deadline: stdout/stderr drain here while the stdin writer
        // progresses concurrently. If the deadline fires first, this future is
        // dropped (closing the retained pipes) while `child` stays owned
        // outside so abort paths still terminate the ACTUAL container and reap
        // the client.
        let max_output_bytes = profile.ceilings.max_output_bytes;
        let max_stderr_bytes = profile.ceilings.max_output_bytes;

        let stdout_pipe = child.stdout.take();
        let stderr_pipe = child.stderr.take();

        let drain_outcome = tokio::select! {
            outcome = drain_and_wait(
                &mut child,
                stdout_pipe,
                stderr_pipe,
                max_output_bytes,
                max_stderr_bytes,
            ) => Some(outcome),
            () = tokio::time::sleep_until(deadline) => None,
        };
        let stream_result = match drain_outcome {
            Some(outcome) => outcome,
            None => {
                return Err(Self::abort_with_timeout(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    start_instant.elapsed().as_secs(),
                    max_wall_clock_seconds,
                )
                .await);
            }
        };

        // 8. Join the stdin writer INSIDE the same global deadline. A blocked
        // writer can never extend execution past the ceiling: on expiry it is
        // aborted and the actual container is terminated. No unbounded
        // `writer_task.await` exists anywhere past the deadline, and a
        // completed handle is taken (never polled again by abort paths).
        let write_outcome = tokio::select! {
            res = writer_task.as_mut().expect("writer task pending") => Some(res),
            () = tokio::time::sleep_until(deadline) => None,
        };
        match write_outcome {
            None => {
                return Err(Self::abort_with_timeout(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    start_instant.elapsed().as_secs(),
                    max_wall_clock_seconds,
                )
                .await);
            }
            Some(Err(_)) => {
                writer_task.take();
                return Err(Self::abort_with_error(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    SandboxError::IO {
                        detail: "Sandbox stdin writer task terminated unexpectedly".to_string(),
                    },
                )
                .await);
            }
            Some(Ok(Err(e))) => {
                writer_task.take();
                return Err(Self::abort_with_error(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    SandboxError::IO {
                        detail: format!("Failed writing scoped input to sandbox stdin: {e}"),
                    },
                )
                .await);
            }
            Some(Ok(Ok(()))) => {
                writer_task.take();
            }
        }

        let (stdout_bytes, stderr_bytes, status) = match stream_result {
            StreamResult::Success {
                stdout,
                stderr,
                status,
            } => (stdout, stderr, status),
            StreamResult::StdoutOverflow { attempted_bytes } => {
                // Hard ceiling crossed during stdout streaming: terminate the
                // ACTUAL container and reap the client (fail closed when
                // termination cannot be established).
                return Err(Self::abort_with_error(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    SandboxError::ResourceViolation {
                        resource: "stdout_output_bytes".to_string(),
                        limit: format!("{max_output_bytes} bytes"),
                        detail: format!(
                            "Sandbox stdout exceeded hard output ceiling of {max_output_bytes} bytes during consumption (attempted {attempted_bytes} bytes)"
                        ),
                    },
                )
                .await);
            }
            StreamResult::StderrOverflow { attempted_bytes } => {
                // Hard ceiling crossed during stderr streaming: terminate the
                // ACTUAL container and reap the client (fail closed when
                // termination cannot be established).
                return Err(Self::abort_with_error(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    SandboxError::ResourceViolation {
                        resource: "stderr_output_bytes".to_string(),
                        limit: format!("{max_stderr_bytes} bytes"),
                        detail: format!(
                            "Sandbox stderr exceeded hard output ceiling of {max_stderr_bytes} bytes during consumption (attempted {attempted_bytes} bytes)"
                        ),
                    },
                )
                .await);
            }
            StreamResult::IoError(detail) => {
                return Err(Self::abort_with_error(
                    &backend_program,
                    &container_name,
                    &mut child,
                    &mut writer_task,
                    SandboxError::IO { detail },
                )
                .await);
            }
        };

        let stderr_str = String::from_utf8_lossy(&stderr_bytes).to_string();

        // 6. Check backend exit status. A missing parser binary/image inside
        // the container exits non-zero here and is NEVER treated as success.
        if !status.success() {
            let code = status.code();

            #[cfg(unix)]
            let signal = {
                use std::os::unix::process::ExitStatusExt;
                status.signal()
            };
            #[cfg(not(unix))]
            let signal: Option<i32> = None;

            // Check for OOM exit conditions (exit code 137, SIGKILL (9), or stderr diagnostic).
            if code == Some(137)
                || signal == Some(9)
                || stderr_str.to_lowercase().contains("out of memory")
                || stderr_str.to_lowercase().contains("oom-killer")
            {
                return Err(SandboxError::OutOfMemory { detail: stderr_str });
            }

            // Check for CPU limit signal SIGXCPU (24).
            if signal == Some(24) {
                return Err(SandboxError::ResourceViolation {
                    resource: "CPU".to_string(),
                    limit: format!("{}s", profile.ceilings.max_wall_clock_seconds),
                    detail: "Sandbox killed by SIGXCPU (CPU time limit exceeded)".to_string(),
                });
            }

            return Err(SandboxError::ProcessCrash {
                exit_code: code,
                signal,
                stderr: stderr_str,
            });
        }

        // 7. Verify hard output size bound on received bytes.
        if stdout_bytes.len() > profile.ceilings.max_output_bytes {
            return Err(SandboxError::ResourceViolation {
                resource: "stdout_output_bytes".to_string(),
                limit: format!("{} bytes", profile.ceilings.max_output_bytes),
                detail: format!(
                    "Output size {} bytes exceeds bound {}",
                    stdout_bytes.len(),
                    profile.ceilings.max_output_bytes
                ),
            });
        }

        // 8. Deserialize JSON output envelope.
        let output: SandboxOutput =
            serde_json::from_slice(&stdout_bytes).map_err(|e| SandboxError::MalformedOutput {
                detail: format!("Failed to parse sandbox JSON output: {e}"),
            })?;

        // 9. Authoritative validation against input and domain bounds.
        output
            .validate_against_input(input)
            .map_err(SandboxError::OutputValidation)?;

        Ok(output)
    }
}
