//! RFC 9457 Problem Details for HTTP APIs error shell.
//!
//! Provides standardized, safe, machine-readable and human-readable error payloads.
//! Guarantees that internal stack traces, filesystem paths, and secrets are never returned.

use axum::http::{HeaderValue, StatusCode, Uri, header};
use axum::response::{IntoResponse, Response};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use w014_observability::{CorrelationId, HEADER_CORRELATION_ID, HEADER_REQUEST_ID};

/// Standard media type for RFC 9457 Problem Details responses.
pub const PROBLEM_JSON_MEDIA_TYPE: &str = "application/problem+json";

/// Standard RFC 9457 Problem Details payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ProblemDetails {
    /// A URI reference that identifies the problem type.
    #[serde(rename = "type")]
    pub type_uri: String,
    /// A short, human-readable summary of the problem type.
    pub title: String,
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    pub status: u16,
    /// A human-readable explanation specific to this occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// A URI reference that identifies the specific occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Stable platform error classification code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Correlation identifier for request traceability.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
}

impl ProblemDetails {
    /// Creates a ProblemDetails payload for a Not Found (404) error.
    #[must_use]
    pub fn not_found(detail: impl Into<String>, instance: Option<String>) -> Self {
        Self {
            type_uri: "urn:w014:error:not-found".to_string(),
            title: "Not Found".to_string(),
            status: StatusCode::NOT_FOUND.as_u16(),
            detail: Some(detail.into()),
            instance,
            code: Some("NOT_FOUND".to_string()),
            correlation_id: None,
        }
    }

    /// Creates a ProblemDetails payload for a Bad Request (400) error.
    #[must_use]
    pub fn bad_request(detail: impl Into<String>, instance: Option<String>) -> Self {
        Self {
            type_uri: "urn:w014:error:bad-request".to_string(),
            title: "Bad Request".to_string(),
            status: StatusCode::BAD_REQUEST.as_u16(),
            detail: Some(detail.into()),
            instance,
            code: Some("BAD_REQUEST".to_string()),
            correlation_id: None,
        }
    }

    /// Creates a ProblemDetails payload for a Method Not Allowed (405) error.
    #[must_use]
    pub fn method_not_allowed(detail: impl Into<String>, instance: Option<String>) -> Self {
        Self {
            type_uri: "urn:w014:error:method-not-allowed".to_string(),
            title: "Method Not Allowed".to_string(),
            status: StatusCode::METHOD_NOT_ALLOWED.as_u16(),
            detail: Some(detail.into()),
            instance,
            code: Some("METHOD_NOT_ALLOWED".to_string()),
            correlation_id: None,
        }
    }

    /// Creates a ProblemDetails payload for an Internal Server Error (500).
    /// Always masks internal details to prevent leaking internal state.
    #[must_use]
    pub fn internal_server_error(instance: Option<String>) -> Self {
        Self {
            type_uri: "urn:w014:error:internal-error".to_string(),
            title: "Internal Server Error".to_string(),
            status: StatusCode::INTERNAL_SERVER_ERROR.as_u16(),
            detail: Some("An unexpected internal error occurred. Please contact support with the correlation ID.".to_string()),
            instance,
            code: Some("INTERNAL_SERVER_ERROR".to_string()),
            correlation_id: None,
        }
    }

    /// Injects a correlation identifier into the problem details.
    #[must_use]
    pub fn with_correlation_id(mut self, correlation_id: &CorrelationId) -> Self {
        self.correlation_id = Some(correlation_id.as_str().to_string());
        self
    }
}

/// Foundation platform error enumeration.
#[derive(Debug, thiserror::Error)]
pub enum ApiError {
    #[error("Not Found: {detail}")]
    NotFound {
        detail: String,
        instance: Option<String>,
    },
    #[error("Bad Request: {detail}")]
    BadRequest {
        detail: String,
        instance: Option<String>,
    },
    #[error("Method Not Allowed: {detail}")]
    MethodNotAllowed {
        detail: String,
        instance: Option<String>,
    },
    #[error("Internal Server Error")]
    InternalServerError { instance: Option<String> },
}

impl ApiError {
    #[must_use]
    pub fn to_problem_details(&self) -> ProblemDetails {
        match self {
            Self::NotFound { detail, instance } => {
                ProblemDetails::not_found(detail.clone(), instance.clone())
            }
            Self::BadRequest { detail, instance } => {
                ProblemDetails::bad_request(detail.clone(), instance.clone())
            }
            Self::MethodNotAllowed { detail, instance } => {
                ProblemDetails::method_not_allowed(detail.clone(), instance.clone())
            }
            Self::InternalServerError { instance } => {
                ProblemDetails::internal_server_error(instance.clone())
            }
        }
    }
}

impl IntoResponse for ProblemDetails {
    fn into_response(self) -> Response {
        let status = StatusCode::from_u16(self.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
        let corr_id_opt = self.correlation_id.clone();
        let body_json = serde_json::to_string(&self).unwrap_or_else(|_| {
            r#"{"type":"urn:w014:error:internal-error","title":"Internal Server Error","status":500}"#
                .to_string()
        });

        let mut res = (status, body_json).into_response();
        res.headers_mut().insert(
            header::CONTENT_TYPE,
            HeaderValue::from_static(PROBLEM_JSON_MEDIA_TYPE),
        );

        if let Some(hdr_val) = corr_id_opt
            .as_deref()
            .and_then(|id| HeaderValue::from_str(id).ok())
        {
            res.headers_mut()
                .insert(HEADER_CORRELATION_ID, hdr_val.clone());
            res.headers_mut().insert(HEADER_REQUEST_ID, hdr_val);
        }

        res
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        self.to_problem_details().into_response()
    }
}

/// Fallback handler for unmatched routes, returning standard RFC 9457 404 Problem Details.
pub async fn fallback_404_handler(
    uri: Uri,
    corr_id: Option<axum::extract::Extension<CorrelationId>>,
) -> impl IntoResponse {
    let mut problem = ProblemDetails::not_found(
        format!("The requested path '{}' was not found.", uri.path()),
        Some(uri.path().to_string()),
    );

    if let Some(axum::extract::Extension(id)) = corr_id {
        problem = problem.with_correlation_id(&id);
    }

    problem
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_problem_details_not_found() {
        let problem = ProblemDetails::not_found("Resource missing", Some("/unknown".into()));
        assert_eq!(problem.status, 404);
        assert_eq!(problem.title, "Not Found");
        assert_eq!(problem.detail.as_deref(), Some("Resource missing"));
        assert_eq!(problem.instance.as_deref(), Some("/unknown"));
        assert_eq!(problem.code.as_deref(), Some("NOT_FOUND"));
    }

    #[test]
    fn test_internal_error_masks_details() {
        let problem = ProblemDetails::internal_server_error(Some("/crash".into()));
        assert_eq!(problem.status, 500);
        assert!(!problem.detail.unwrap().contains("panic"));
    }

    #[test]
    fn test_problem_details_serialization() {
        let corr_id = CorrelationId::generate();
        let problem = ProblemDetails::bad_request("invalid input", Some("/api/test".into()))
            .with_correlation_id(&corr_id);

        let json = serde_json::to_string(&problem).unwrap();
        assert!(json.contains(r#""type":"urn:w014:error:bad-request""#));
        assert!(json.contains(r#""status":400"#));
        assert!(json.contains(r#""title":"Bad Request""#));
        assert!(json.contains(corr_id.as_str()));
    }
}
